/base_height_map_node:
  ros__parameters:
    input_topic: "/elevation_mapping_node/elevation_map_filter"
    output_topic: "/elevation_mapping_node/base_height_map"
    valid_output_topic: "/elevation_mapping_node/base_height_map_valid"
    input_layer: "inpaint"

    source_frame: "odom"
    target_frame: "base"

    resolution: 0.1
    x_min: -1.0
    x_max: 2.0
    y_min: -1.0
    y_max: 1.0

    publish_rate: 50.0
    unknown_value: .nan
    interpolation: "nearest"
    use_latest_tf: true
    tf_timeout: 0.05
